[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm --prefix server ci --include=dev"]

[phases.build]
cmds = ["npm --prefix server run build"]

[start]
cmd = "npm --prefix server run start:prod"

[variables]
NPM_CONFIG_PRODUCTION = "false"
